### ISSUE TITLE
Bind Failure

### ISSUE THREAD

**Issue by KirbyJames** [bablokb/pi-webradio#4]
Hi, I read your interesting article in the new MakerSpace magazine.

I've installed pi-webradio and it works fine using 

     pi-webradio.py  -d

However, when I install it as a service I get a bind error as pi-webradio.py is running before the OS has set up the ethernet link (in my case on192.168.1.214).

I'm running on a Rpi4 with 4GB of memory.

Any suggestions appreciated.

Kirby

syslog extract

Jul  2 17:15:44 blue systemd[1]: Started pi-webradio.

Jul  2 17:15:47 blue pi-webradio.py[388]: Exception in thread Thread-5:
Jul  2 17:15:47 blue pi-webradio.py[388]: Traceback (most recent call last):
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jul  2 17:15:47 blue pi-webradio.py[388]:     self.run()
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Jul  2 17:15:47 blue pi-webradio.py[388]:     self._target(*self._args, **self._kwargs)
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/local/bin/../lib/webradio/SRWebServer.py", line 208, in run
Jul  2 17:15:47 blue pi-webradio.py[388]:     self._server = make_server(self._host,self._port,self._flask,
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
Jul  2 17:15:47 blue pi-webradio.py[388]:     return ThreadedWSGIServer(
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
Jul  2 17:15:47 blue pi-webradio.py[388]:     HTTPServer.__init__(self, server_address, handler)
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
Jul  2 17:15:47 blue pi-webradio.py[388]:     self.server_bind()
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
Jul  2 17:15:47 blue pi-webradio.py[388]:     socketserver.TCPServer.server_bind(self)
Jul  2 17:15:47 blue pi-webradio.py[388]:   File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
Jul  2 17:15:47 blue pi-webradio.py[388]:     self.socket.bind(self.server_address)
Jul  2 17:15:47 blue pi-webradio.py[388]: **OSError: [Errno 99] Cannot assign requested address**

Jul  2 17:15:48 blue dhcpcd[548]: eth0: carrier acquired
Jul  2 17:15:48 blue kernel: [   11.513659] bcmgenet fd580000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
Jul  2 17:15:48 blue dhcpcd[548]: eth0: adding address fe80::c040:5282:17c5:dc71
Jul  2 17:15:48 blue dhcpcd[548]: **eth0: probing address 192.168.1.214/24**

Jul  2 17:16:59 blue systemd[1]: Stopping pi-webradio...
Jul  2 17:16:59 blue pi-webradio.py[388]: Traceback (most recent call last):
Jul  2 17:16:59 blue pi-webradio.py[388]:   File "/usr/local/bin/pi-webradio.py", line 144, in <module>
Jul  2 17:16:59 blue pi-webradio.py[388]:     signal.pause()
Jul  2 17:16:59 blue pi-webradio.py[388]:   File "/usr/local/bin/../lib/webradio/SRWebRadio.py", line 260, in signal_handler
Jul  2 17:16:59 blue pi-webradio.py[388]:     self.cleanup()
Jul  2 17:16:59 blue pi-webradio.py[388]:   File "/usr/local/bin/../lib/webradio/SRWebRadio.py", line 270, in cleanup
Jul  2 17:16:59 blue pi-webradio.py[388]:     self._server.stop()
Jul  2 17:16:59 blue pi-webradio.py[388]:   File "/usr/local/bin/../lib/webradio/SRWebServer.py", line 194, in stop
Jul  2 17:16:59 blue pi-webradio.py[388]:     self._server.shutdown()
Jul  2 17:16:59 blue pi-webradio.py[388]: AttributeError: 'WebServer' object has no attribute '_server'

Jul  2 17:18:29 blue systemd[1]: pi-webradio.service: State 'stop-sigterm' timed out. Killing.
Jul  2 17:18:29 blue systemd[1]: pi-webradio.service: Killing process 388 (pi-webradio.py) with signal SIGKILL.
Jul  2 17:18:29 blue systemd[1]: pi-webradio.service: Killing process 607 (pi-webradio.py) with signal SIGKILL.
Jul  2 17:18:29 blue systemd[1]: pi-webradio.service: Main process exited, code=killed, status=9/KILL
Jul  2 17:18:29 blue systemd[1]: pi-webradio.service: Failed with result 'timeout'.
Jul  2 17:18:29 blue systemd[1]: Stopped pi-webradio.
Jul  2 17:18:29 blue systemd[1]: pi-webradio.service: Consumed 1.253s CPU time.

**Comment by bablokb** [comment]
Hi,

I assume you explicitly listen to an IP of the network and not 0.0.0.0. 

To solve the problem, please check https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/. If you are not interested in the  details, scroll down to the "Cut the crap!..."-section.

There are simpler things to try first: change the `[Install]`-section in `/etc/systemd/pi-webradio.service` to `WantedBy=multi-user.taget` instead of `WantedBy=network.target`. Or configure your system to use a fixed IP instead of using dhcpd.

If all this does not help, you could add a script with `ExecStartPre=` to the service-definition that just loops until the network is up.  Very hacky and not recommended, since letting systemd handle the problem is the correct thing to do.

If you need additional help, just ask.

Bernhard

**Comment by KirbyJames** [comment]
Bernhard,

Thanks for your reply.  I've managed to make it work using a cron file containing

`@reboot  /home/pi/pi-webradio.sh`

with pi-webradio.sh containing


```
#!/bin/bash

sleep 10
/usr/bin/python3 /usr/local/bin/pi-webradio.py -d  >> /home/pi/pi-webradio.log  2>&1
```
Many thanks for your help.

Kirby
