### ISSUE TITLE
Channel List doesn't refresh

### ISSUE THREAD

**Issue by Gurkenpetr** [bablokb/pi-webradio#5]
Hi! I just did a clean installation of pi-webradio and everything seems to work fine so far. I also updated the pi-webradio.channels file and uploaded the station logos, but the channel list doesn't update in the tool even though i restarted the service and rebooted.

Is there any kind of hint that you could give?

**Comment by bablokb** [comment]
The installation-routine keeps an existing `/etc/pi-webradio.channels` and copies the new one to `/etc/pi-webradio.channels.new`. Maybe this is the problem.

**Comment by Gurkenpetr** [comment]
Thanks for the quick answer, @bablokb!

As this was a totally new installation on a new sd card I guess this may not be related.

This is my channel file

`[
  { "name": "NDR 1",
    "url":  "https://www.ndr.de/resources/metadaten/audio/m3u/ndr1niedersachsen.m3u",
    "logo": "ndr1.png"
  },

  { "name": "NDR 2",
    "url":  "https://www.ndr.de/resources/metadaten/audio/m3u/ndr2.m3u",
    "logo": "ndr2.png"
  },

  { "name": "N-JOY",
    "url":  "https://www.ndr.de/resources/metadaten/audio/m3u/n-joy.m3u",
    "logo": "njoy.png"
  },

  { "name": "NDR Info",
    "url":  "https://www.ndr.de/resources/metadaten/audio/m3u/ndrinfo.m3u",
    "logo": "ndrinfo.png"
  }       
]
`
(stored in /files/etc)

Could this be a total rookie mistake topic? :-/

**Comment by bablokb** [comment]
Yes, it should be in `/etc`. Or you put in in `files/etc` and then run the installation. `files/etc` is within the cloned directory and the installation routine mainly copies everything below `files/` to the system.

**Comment by Gurkenpetr** [comment]
OK, I reinstalled on a clean system, implemented the channel file before the installation and now it's working like a charm! 

Thanks for your work @bablokb!
